USE asset;

CREATE TABLE IF NOT EXISTS epo (
  TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  IP INT UNSIGNED NOT NULL DEFAULT 0,
  HOSTNAME varchar(50),
  IS_LAPTOP boolean,
  OS varchar(15),
  USERS varchar(15),
  PRIMARY KEY (IP)
);
